### ISSUE TITLE
[1.19.2 | Suggestion] Ability to turn off item rendering/limit it to one

### ISSUE THREAD

**Issue by gokayerez** [AbsolemJackdaw/AppleCrates#16]
I help run a server where we have a market. Since we have a LOT of crates, it lags the game quite a lot. Could it be possible in the config to limit the item rendering to 1 item in the create? Or even an alternative system where it doesn't render anything, but simply displays the name of the item? Thanks!

**Comment by AbsolemJackdaw** [comment]
Hi ! Lag is never fun. 
what loader are you using ? 
if you are using forge, which one of the rendering options are you using ? 
the rendering of the items should only happen client side, and should not lag the server at all. 
if the server is lagging because of the crates, I will have to look into the inventory logic. 
Can you use Spark to check the amount of lag the crates are creating ?
feel free to join the discord and ping me to have a 101 direct talk with me, we can find out what's causing the lag together

**Comment by gokayerez** [comment]
no, no, the lag is client-side, definitely not server :) i just wish there was a way to decrease it, that's all

**Comment by AbsolemJackdaw** [comment]
i'll take a look at the rendering code. 
I'd still like to know the loader and mod version you are using !

**Comment by gokayerez** [comment]
it's forge, i'm using 2.9.0, thank you!
